---
title: "Assignment 5"
author: "40902457 and 51237579"
output: pdf_document
---



```{r loadlibs, echo=FALSE, message=FALSE, warning=FALSE}
# This block will not show in your report.  It just loads things and gets you 
# ready.

# Put all libraries here. 
library( texreg )
library( arm )
library( lme4 )
library( foreign )
library( plyr)
library( sqldf) 
library( foreign )
library( sqldf)
library( ggplot2 ) 
library( scales )
library( pander)
library( nlme)
library( lattice)
library( Hmisc)
library(formatR)
library(knitr)
library(effects)

opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)

# Put global display options here
options(digits=2)

# This flag is to control whether analytic code blocks should display
# the code itself.
# When turning in work, you should knit two pdfs, 
# with this variable set to FALSE and TRUE respectively.
# When FALSE you have a nice report with results only.  When TRUE you have 
# the code itself so we can see what you did.
show.code = FALSE
# show.code = TRUE # just comment this line out to make it false

# This controls whether the code for making plots should be shown.
# When turning in your work, you should leave this as FALSE, 
# unless there is something about your plots that is not working as it should.
show.plot.code = show.code
show.plot.code = FALSE #  comment this out to make it follow the overall config


# You might put code to load data and get it ready for analysis here.
# ...
 
```





```{r include=FALSE}
#PREPARING DATA

# set working directory
setwd("/Users/vinhtony2808/Documents/Stat151")
getwd()

#Call in Data
Data5 <- read.csv('assignment_5_data.csv')
 
str(Data5)


```



#Q1: Assess willingness to tutor by gender
```{r, echo=TRUE, results='asis', message=FALSE, warning=FALSE}
#Q1:Fit a model predicting willingness to tutor another student based on the respondent's gender. Partially pool both the intercept and the gender effect.
Q1 <-  glmer( tutor ~ gender + (gender|school), data=Data5, family=binomial(link="logit") )

texreg(Q1)

#compute confidence intervals
Q1_ConfInt <- confint(Q1)
exp(Q1_ConfInt)

#plot the predicted probabilities
plot(allEffects(Q1))

#Q1.2 fix weird issue
  #issue: there's a perfectively negative correlation between intercept and slope
  VarCorr(Q1)
  
#Fix: Normally, our fix is to center our means, but we can't do that with gender, so we'll add an interaction term for the proportion of male students

#Create male indicator var
  Data5$male[Data5$gender=='Female'] <-0
  Data5$male[Data5$gender=='Male'] <-1
  
#Create school-level dataset that has proportion of male students
schoolMale <- sqldf('select distinct school, 
                                     avg(male) as propMale
                     from Data5 
                     group by school')
 
Data5 <- merge(Data5,schoolMale,by="school")
  
Q1.2 <- glmer( tutor ~ gender*propMale + (gender|school), data=Data5, family=binomial(link="logit") )

texreg(Q1.2)

VarCorr(Q1.2)

#basic answer for now: girls have a higher probability 

```



\newpage
#Q2: Visualize school variation
```{r, echo=TRUE, results='asis', message=FALSE, warning=FALSE}
#Q2: Using the raw data, generate school-level proportions of boys and girls willingness to tutor. Make a scatterplot of these pairs of values.
#Create two visuals
  #Both school level
  #Both plot girsl vs boys
  #One is the raw proportion of students that were willing, i.e., average(tutor2) by school and gender
  #One is the predicted probablity

#DATA PREPARATION
  Data5$tutor2[Data5$tutor=='No'] <-0
  Data5$tutor2[Data5$tutor=='Yes'] <-1
  
  #table(Data5$tutor2)
  #table(Data5$tutor)
   
  #Create dataset for the predicted probabilities 
  #specifying type="response" returns predictions on the probability scale
  Data5$predprobs <- predict(Q1, newdata=Data5, type="response" )
  
  #Create 2 school-level datasets with:
    #average proportion of students willing to tutor (girlprop and boyprop)
    #predicted probability predprobs which we'll rename as girlpred/boypred
  #Separately for girls and boys
    girls <- sqldf("select distinct school,
                                   avg(tutor2) as girlprop,
                                   predprobs   as girlpred
                      from Data5 
                      where gender = 'Female'
                      group by school" )
   
    boys <- sqldf("select distinct school,
                                   avg(tutor2) as boyprop,
                                   predprobs   as boypred
                      from Data5 
                      where gender = 'Male'
                      group by school")
   
    #merge those two datasets
    gendercombined <-merge(girls,boys,by="school")
   
#CREATE PLOTS
#Q2.1 raw probabilities plot
ggplot(data=gendercombined, aes(x=girlprop, y=boyprop)) + 
  geom_point()+
  ylim(.7,1) +
  xlim(.7,1) +
  labs(title="Q2.1: Raw school-level proportions of\n willingness to tutor\n boys vs girls"
          ,x="Willingness to tutor\n (girls)"
          ,y="Willingness to tutor\n (boys)") 

#Q2.2 predicted probabilities plot
ggplot(data=gendercombined, aes(x=girlpred, y=boypred)) + 
  geom_point() +
  ylim(.7,1) +
  xlim(.7,1) +
  labs(title="Q2.2: Predicted school-level probabilities of\n willingness to tutor\n boys vs girls"
          ,x="Willingness to tutor\n (girls)"
          ,y="Willingness to tutor\n (boys)") 
```

\newpage
#Q3: Add level-2 covariates to the model
```{r, echo=TRUE, results='asis', message=FALSE, warning=FALSE}
#Q3. Design and implement a model potentially incorporating school-level mean sense of belonging and school type (make sure that public schools are the reference category). Be sure to center covariates as needed to give an interpretation for your intercept terms.

#Need to center school-lever belong
#First compute grand mean across all schools which we'll subtract from the school level mean
Data5$belongGrandMean <- mean(Data5$belong,na.rm=TRUE)

#Generate school-level mean sense of belonging
schoolBelong <- sqldf('select distinct school,
                               avg(belong) as avgBelong,
                               avg(belong) - belongGrandMean as centerBelong 
                          from Data5
                          group by school')

#Merge the school-level sense of belong to child-level data
Data5 <- merge(Data5,schoolBelong,by="school")

#Currently, 1 = Private, 2 = Public, and 3 = Religious
#We want Public to be the reference category, so we're going to relevel
Data5 <- within(Data5, type <- relevel(type, ref = 2))

Q3 <-  glmer(tutor ~ gender + type + centerBelong  + (gender|school), data=Data5, family=binomial(link="logit"))

texreg(Q3)
 
#compute confidence intervals
Q3_ConfInt <- confint(Q3)
exp(Q3_ConfInt)

#plot the predicted probabilities
plot(allEffects(Q3))

 


```
 

\newpage
#Q4: Visualize the model
```{r, echo=TRUE, results='asis', message=FALSE, warning=FALSE}
  
#Create plot to show how your level-2 covariates relate to this probability
Data5$predprobs2 <- predict(Q3, newdata=Data5, type="response" )

ggplot( data=Data5, aes( x=avgBelong, y=predprobs2, group=type, color=gender ) ) +
      labs(title="Q4: Relationship between mean school-level belonging\n and predicted probability of willingness to tutor\n by school type"
          ,x="Mean school-level belonging"
          ,y="Predicted probability of\n willingness to tutor")+
      facet_wrap( ~ type ) +
      geom_point()
```
 
\newpage
#Q5: Add an interaction to the model
```{r, echo=TRUE, results='asis', message=FALSE, warning=FALSE}

#Add interactions between gender and school type and between gender and school-level sense of belonging to the model
Q5 <-  glmer(tutor ~ gender*(type + centerBelong)  + (gender|school), data=Data5, family=binomial(link="logit"))

texreg(Q5)

#compute confidence intervals
Q5_ConfInt <- confint(Q5)
exp(Q5_ConfInt)

#plot the predicted probabilities
plot(allEffects(Q5))

```
 

Acknowledgements:
90880525
10903106 